### ISSUE TITLE
IO error messages on conversion and check

### ISSUE THREAD

**Issue by MCDad** [alejandroliu/pmimporter#2]
Hi

I'm converting MCPE files (v0.12.2) and I'm getting the following:

----------  using convert   ----------

./bin/php5/bin/php pmimporter_v2.0dev1.phar convert ./best ./worlds/best
Number of Chunks to Copy: 246
Threads: 4
....
Fatal error: Uncaught exception 'LevelDBException' with message 'IO error: lock ./best//db/LOCK: Resource temporarily unavailable' in phar:///home/pocketmine/pmimporter_v2.0dev1.phar/classlib/pmimporter/leveldb/LevelDB.php:137
Stack trace:
#0 phar:///home/pocketmine/pmimporter_v2.0dev1.phar/classlib/pmimporter/leveldb/LevelDB.php(137): LevelDB->__construct('./best//db', Array)
#1 phar:///home/pocketmine/pmimporter_v2.0dev1.phar/scripts/convert.php(160): pmimporter\leveldb\LevelDB->getChunk(-1, -3, 0)
#2 phar:///home/pocketmine/pmimporter_v2.0dev1.phar/scripts/convert.php(181): copyNextChunk()
#3 phar:///home/pocketmine/pmimporter_v2.0dev1.phar/main.php(39): require_once('phar:///home/po...')
#4 /home/pocketmine/pmimporter_v2.0dev1.phar(1): include('phar:///home/po...')
#5 {main}

  thrown in phar:///home/pocketmine/pmimporter_v2.0dev1.phar/classlib/pmimporter/leveldb/LevelDB.php on line 137

------- repeated many times  ------

----------- using check ----------

./bin/php5/bin/php ./pmimporter_v2.0dev1.phar check ./best
FORMAT:    LevelDB
SEED:      580730
Generator: 
Presets:  
Spawn:     4,128,0

Fatal error: Uncaught exception 'LevelDBException' with message 'IO error: lock ./best/db/LOCK: Resource temporarily unavailable' in phar:///home/pocketmine/pmimporter_v2.0dev1.phar/classlib/pmimporter/leveldb/LevelDB.php:118
Stack trace:
#0 phar:///home/pocketmine/pmimporter_v2.0dev1.phar/classlib/pmimporter/leveldb/LevelDB.php(118): LevelDB->__construct('./best/db', Array)
#1 phar:///home/pocketmine/pmimporter_v2.0dev1.phar/scripts/check.php(53): pmimporter\leveldb\LevelDB->getChunks()
#2 phar:///home/pocketmine/pmimporter_v2.0dev1.phar/main.php(39): require_once('phar:///home/po...')
#3 /home/pocketmine/pmimporter_v2.0dev1.phar(1): include('phar:///home/po...')
#4 {main}

  thrown in phar:///home/pocketmine/pmimporter_v2.0dev1.phar/classlib/pmimporter/leveldb/LevelDB.php on line 118
## Thrown just the once

Using pmimporter_v2.0dev1 and PHP5.6 on Raspberry Pi2+.

Not sure if its pmimporter or the file format.  mcregion format files are appearing in the output folder.

Thanks

**Comment by alejandroliu** [comment]
I have not gotten this error.  Can you share the files you are trying to convert?

**Comment by MCDad** [comment]
Alex,  just sent you a Google drive link to the files. Cheers MCDad

**Comment by alejandroliu** [comment]
Sorry, I have not received any link.

**Comment by MCDad** [comment]
Does this work?  https://drive.google.com/open?id=0B7EdbKx5c85vOVRnZlEyRy01UzA

**Comment by MCDad** [comment]
Dooh Button troubles

**Comment by alejandroliu** [comment]
I am having problems with the synchronisation mechanisms.  (I get a deadlock somewhere).  For the moment disable threading (--threads=1).

**Comment by MCDad** [comment]
Thanks will do. But I'm away for a few days. Will try when I get home.
Cheers
